FROM docker.io/bats/bats:1.14.0@sha256:5322b877351fda0cc435de8c6116de7d0a2ec79d7c680132a0ef329a633bc66f

USER root

RUN apk add --no-cache \
        coreutils \
        docker-cli \
        openssl \
        util-linux
